### ISSUE TITLE
Using torchrun launcher instead of detectron's raises AuthenticationError('digest received was wrong')

### ISSUE THREAD

**Issue by LeungTsang** [ppwwyyxx/RAM-multiprocess-dataloader#5]
Hi Yuxin, 
Thank you for your very inspiring blog. I can reproduce your result with the original code. I am trying to adapt the solution for the multi-GPU case to the launcher of pytorch 2.0 itself (https://github.com/LeungTsang/RAM-multiprocess-dataloader). I almost keep everything the same but simply read the rank, local_rank, world_size variables from the environment variables provided by torchrun and initialize the process group by `dist.init_process_group(backend='nccl')`. However, running `torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0  main-multigpu-sharedmem.py`, I got an error:

> Traceback (most recent call last):
  File "/home/lzeng/.conda/envs/torch2/lib/python3.10/multiprocessing/resource_sharer.py", line 138, in _serve
Traceback (most recent call last):
  File "/home/lzeng/testspace/RAM-multiprocess-dataloader/main-multigpu-sharedmem.py", line 59, in <module>
    main()    
  File "/home/lzeng/testspace/RAM-multiprocess-dataloader/main-multigpu-sharedmem.py", line 26, in main
with self._listener.accept() as conn:
  File "/home/lzeng/.conda/envs/torch2/lib/python3.10/multiprocessing/connection.py", line 465, in accept
    ds = DatasetFromList(TorchShmSerializedList(
  File "/home/lzeng/testspace/RAM-multiprocess-dataloader/serialize.py", line 99, in __init__
    self._addr, self._lst = mp.reduction.ForkingPickler.loads(handle)
  File "/home/lzeng/.conda/envs/torch2/lib/python3.10/site-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    deliver_challenge(c, self._authkey)
  File "/home/lzeng/.conda/envs/torch2/lib/python3.10/multiprocessing/connection.py", line 745, in deliver_challenge
    fd = df.detach()
  File "/home/lzeng/.conda/envs/torch2/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/home/lzeng/.conda/envs/torch2/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/home/lzeng/.conda/envs/torch2/lib/python3.10/multiprocessing/connection.py", line 508, in Client
    raise AuthenticationError('digest received was wrong')
multiprocessing.context.AuthenticationError: digest received was wrong
    answer_challenge(c, authkey)
  File "/home/lzeng/.conda/envs/torch2/lib/python3.10/multiprocessing/connection.py", line 759, in answer_challenge
    raise AuthenticationError('digest sent was rejected')
multiprocessing.context.AuthenticationError: digest sent was rejected

Strangely, it seems a unique problem with torchrun launcher, ForkingPickler and pytorch tensor(Any dummy tensor to broadcast among workers will trigger the error). Using TorchShmSerializedList(NumpySerializedList) instead of TorchShmSerializedList(TorchSerializedList) may resolve it but unfavorably cost more memory. Unfortunately, I cannot find anything related online and it will be highly appreciated if you(or anybody) have more insight into the issue.

**Comment by ppwwyyxx** [comment]
The way torchrun launches workers make them not able to share data among each other. 

Here is a workaround. Call this function in each worker's main:
```python
def local_broadcast_process_authkey():
    if int(os.environ['LOCAL_WORLD_SIZE']) == 1:
        return 
    local_rank = int(os.environ['LOCAL_RANK'])
    authkey = bytes(mp.current_process().authkey)
    all_keys = comm.all_gather(authkey)
    local_leader_key = all_keys[comm.get_rank() - local_rank]
    if authkey != local_leader_key:
        print("Process authkey is different from the key of local leader. This might happen when "
              "workers are launched independently.")
        print("Overwriting local authkey ...")
        mp.current_process().authkey = local_leader_key
```
