### ISSUE TITLE
[Question] Use `ForkingPickler` to pickle/unpickle tensors in shared memory

### ISSUE THREAD

**Issue by chang-l** [ppwwyyxx/RAM-multiprocess-dataloader#6]
Hi, thank you for your great blog! I am new to Python and have a probably very basic question regarding `ForkingPickler`. When I tried to manage the sharing context (tensor) explicitly like the following:
```
if dist.get_rank(group=local_group) == 0:
    x = torch.arange(5)
    handles = [None] + [
           bytes(multiprocessing.reduction.ForkingPickler.dumps(x))
           for _ in range(num_local_process - 1)]
else:
    handles = None

handle = local_scatter(handles)
if dist.get_rank(group=local_group) > 0:       
    x =  multiprocessing.reduction.ForkingPickler.loads(handle)
    print(x)
``` 
I thought it would make tensor `x` in the shared memory, however, it crashed with the following stacktraces:
```
Traceback (most recent call last):
  File "ogbn_products_nc_mpi_shared_mem.py", line 314, in <module>
    x =  multiprocessing.reduction.ForkingPickler.loads(handle)
  File "/usr/local/lib/python3.8/dist-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.8/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 508, in Client
    answer_challenge(c, authkey)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 757, in answer_challenge
    response = connection.recv_bytes(256)        # reject large message
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.8/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
ConnectionResetError: [Errno 104] Connection reset by peer
```
I rewrite the auth_key to sync them in each local group of processes to run with mpirun/torchrun, but I am puzzled on how to correctly use the PyTorch's customized pickler for sharing memory among local processes...
Could you please help explain it?

**Comment by chang-l** [comment]
I guess this is probably because I need to serialize tensor obj to 1D protocol buffer...

**Comment by ppwwyyxx** [comment]
If you can provide a https://stackoverflow.com/help/minimal-reproducible-example, then I can see if the question is interesting and may provide some help.

**Comment by chang-l** [comment]
Hi @ppwwyyxx, thank you for your suggestion. Now, I think I know why it was crashed...

Here is a small repo of the script https://github.com/chang-l/RAM-multiprocess-dataloader/blob/main/main-multigpu-sharedmem-GPUprocs-only.py, and you can run it with `torchrun --nproc_per_node=4 --nnodes=1 --node_rank=0  main-multigpu-sharedmem-GPUprocs-only.py`. On my side, it would crash with the following msg:

```
Traceback (most recent call last):
  File "/Documents/codes/chang-l/RAM-multiprocess-dataloader/main-multigpu-sharedmem-GPUprocs-only.py", line 44, in <module>
    main()
  File "/Documents/codes/chang-l/RAM-multiprocess-dataloader/main-multigpu-sharedmem-GPUprocs-only.py", line 36, in main
    ds = DatasetFromList(TorchShmSerializedList(
  File "/Documents/codes/chang-l/RAM-multiprocess-dataloader/serialize.py", line 99, in __init__
    self._addr, self._lst = mp.reduction.ForkingPickler.loads(handle)
  File "/usr/local/lib/python3.10/dist-packages/torch/multiprocessing/reductions.py", line 307, in rebuild_storage_fd
    fd = df.detach()
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/usr/lib/python3.10/multiprocessing/resource_sharer.py", line 86, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```
I think this is because the main process is unexpectedly closed but other procs are still loading the data. When I added a barrier here: https://github.com/chang-l/RAM-multiprocess-dataloader/blob/3e336d140fea57284a8f3038fcdc77557718dcfa/serialize.py#L102, it can run through.

Do you think it is a good idea to add this line of code?

**Comment by ppwwyyxx** [comment]
Yes, the processes should not be closed before the communication finished.
